CREATE DATABASE db;
USE db;
CREATE TABLE EMPLOYEE (ENO INT PRIMARY KEY,EMPNAME VARCHAR(25),GENDER CHAR(1) CHECK(GENDER IN ('F','M','O')), DOB date ,DOJ date,
DESIGNATION VARCHAR(15),BASIC float,DEPTNO INT,PAN INT ,SENO INT);
CREATE TABLE DEPARTMENT(DEPTNO INT PRIMARY KEY,NAME VARCHAR(25),MENO INT);
CREATE TABLE PROJECT (
PROJNO INT PRIMARY KEY
,NAME VARCHAR(20),
DEPT_NO INT
);
CREATE TABLE WORKSFOR(ENO INT ,PROJNO INT ,DATE_WORKED date,WORKED_HOURS date);
